name: tv_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0-266.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.3.0
  path: ^1.8.3
  http: ^1.1.0
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  # geolocator: ^10.1.0
  # geocoding: ^2.1.1
  intl: ^0.18.1
  get: ^4.6.6
  path_provider: ^2.1.1
  file_picker: ^8.1.4
  audioplayers: ^5.2.1
  just_audio: ^0.9.42
  image_picker: ^1.0.7
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/sounds/bedside-clock-alarm-95792.mp3
